#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Updating NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace \
    --keep="config.yaml passkey.pem appservice-registration-irc.yaml"

#=================================================
# Build
#=================================================
ynh_script_progression "Upgrading the app..."

(
    cd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm i
    $nodejs_dir/node src/generate-signing-key.js > signingkey.jwk

)

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

configured_servers=$(python3 -c "import yaml
with open('$install_dir/config.yaml') as c: c = yaml.load(c, Loader=yaml.SafeLoader)
print(yaml.dump(c['ircService']['servers']))")

### Same as during install

ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

# Try to recover the previously configured IRC servers.
python3 -c "import yaml
with open('$install_dir/config.yaml') as c: c = yaml.load(c, Loader=yaml.SafeLoader)
servers = yaml.safe_load('''$configured_servers''')
c['ircService']['servers'] = servers
print(yaml.dump(c))" > "$install_dir/config.yaml.temp"
mv "$install_dir/config.yaml.temp" "$install_dir/config.yaml"

#=================================================
# REGISTER SYNAPSE APP-SERVICE
#=================================================

ynh_backup_if_checksum_is_different "$install_dir/appservice-registration-irc.yaml"

__ynh_register_matrix_app_service

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="$app daemon for bridging IRC and Matrix messages." --log="/var/log/$app/$app.log"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate  "$app/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
